In [1]:
import torch

In [2]:
randint = torch.randint(-100,100, (6,))
randint

tensor([-53, -28,  -8, -77,  34,  36])

In [3]:
tensor = torch.tensor([[0.1, 1.2], [2.2, 3.1], [4.9, .2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 0.2000]])

In [4]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [5]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [6]:
input = torch.empty(2,3)
input

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [8]:
linspace = torch.linspace(3,10,steps=5)
linspace

tensor([ 3.0000,  4.7500,  6.5000,  8.2500, 10.0000])

In [9]:
logspace = torch.logspace(start = -10, end = 10, steps = 5)
logspace

tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])

In [10]:
eye = torch.eye(4)
eye

tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [11]:
empty = torch.empty((2,3), dtype = torch.int64)
empty_like = torch.empty_like(empty)
empty_like

tensor([[0, 0, 0],
        [0, 0, 0]])

In [30]:
import torch
import numpy as np
import torch.nn as nn
from torch.nn import functional as F
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

cuda


In [13]:
%%time
start_time = time.time()
zeros = torch.zeros(1, 1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f"{elapsed_time:.8f}")

0.00015759
CPU times: total: 0 ns
Wall time: 552 μs


In [14]:
torch_rand1 = torch.rand(100, 100, 100, 100).to(device)
torch_rand2 = torch.rand(100, 100, 100, 100).to(device)
np_rand1 = torch.rand(100, 100, 100, 100)
np_rand2 = torch.rand(100, 100, 100, 100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
# gpu time to do a task
print(f"{elapsed_time:.8f}")


start_time = time.time()

rand = np.multiply(np_rand1, np_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
# cpu time to do a task
print(f"{elapsed_time:.8f}")

# parallel proccessing is a lot quicker for a lot of easy tasks

0.24682736
0.08613968


C:\Users\finla\AppData\Local\Temp\ipykernel_13872\3273287353.py:19: DeprecationWarning: __array_wrap__ must accept context and return_scalar arguments (positionally) in the future. (Deprecated NumPy 2.0)
  rand = np.multiply(np_rand1, np_rand2)


In [15]:
# torch.stack, torch.multinomial, torch.tril, torch.triu, input.T / input.transpose, nn.Linear, torch.cat, F.softmax (show all of the functions/methods with pytorch docs)

# define a probability tensor
probabilities = torch.tensor([0.1,0.9])
# 10% or 0.1 => 0, 90% or 0.9 => 1. each probability points to the idex of the probability in the tensor
# Draw 5 samples from the multinomial distribution
samples = torch.multinomial(probabilities, num_samples = 10, replacement = True)
print(samples)
# There is a 10% chance that we will get a 0 (becuase index 0) and a 90% chance that we will get a 1 (becuase index 1)

tensor([0, 1, 1, 1, 1, 1, 1, 1, 1, 1])


In [16]:
# concatenates two tensors
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim = 0)
out

tensor([1, 2, 3, 4, 5])

In [17]:
# creates a lower matrix
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [18]:
# creates an upper matrix
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [19]:
# creates a upper matrix- useful for exponentiating e to get 0
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [20]:
# exponentiates the last matrix
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [21]:
# transposing a matrix
input = torch.zeros(2, 3, 4)
# swapping 0th dim and 2nd dim
out = input.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [22]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

# stacks the tensors along a new dimension
stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [23]:
# using neural netowrk to train parameters
import torch.nn as nn
sample = torch.tensor([10.,10.,10.])
# fully connected layer with: 3 input features, 3 output features, No bias (bias=False)
# This layer computes:output = 𝑊⋅input where W is a 3×3 weight matrix.
linear = nn.Linear(3, 3, bias=False)
print(linear(sample))

tensor([2.6571, 4.3411, 6.1807], grad_fn=<SqueezeBackward4>)


In [24]:
# softmax function exponentiates the tensor and then divides by the the sum of the exponentiation
# exponentials are better because it Sharpens distinctions, is Always positive, Differentiable, Sensitive to differences, and Models uncertainty
import torch.nn.functional as F

# create a tensor
tensor1 = torch.tensor([1.0, 2.0, 3.0])

# apply softmax using torch.nn.functional.softmax()
softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [25]:
# Initialize an embedding layer
vocab_size = 1000
embedding_dim = 100
embedding = nn.Embedding(vocab_size, embedding_dim)

# Create some input indices
input_indices = torch.LongTensor([1, 5, 3, 2])

# Apply the embedding later
embedded_output = embedding(input_indices)

# The output will be a tensor of shape (4,100), where 4 is the number of inputs
# and 100 is the dimensionality of the embedding vectors
print(embedded_output.shape)

torch.Size([4, 100])


In [26]:
# Multiplying two tensors together
a = torch.tensor([[1,2],[3,4],[5,6]])
b = torch.tensor([[7,8,9],[10,11,12]])
print(a @ b)
print(torch.matmul(a, b))

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])


In [27]:
# integers and floats cannot be multiplied in pytorch- need to cast ints
int_64 = torch.randint(1, (3, 2)).float()
# type int64
float_32 = torch.rand(2,3)
# type float32
result = torch.matmul(int_64, float_32)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [28]:
# views allows us to get the vectors back out of a tensor
a = torch.rand(2, 3, 5)
print(a.shape)
x, y, z = a.shape
a = a.view(x, y, z)
print(x, y, z)
print(a.shape)

torch.Size([2, 3, 5])
2 3 5
torch.Size([2, 3, 5])


In [43]:
x = torch.tensor([-0.05], dtype = torch.float32)
# applies the sigmoid activation function (output- between 0 and 1)
y = F.sigmoid(x)
print(y)

tensor([0.4875])


In [44]:
x = torch.tensor([0], dtype = torch.float32)
# applies the tanh activation function (output- between -1 and 1)
y = F.tanh(x)
print(y)

tensor([0.])
